### ISSUE TITLE
Markdown highlights

### ISSUE THREAD

**Issue by niksingh710** [tiagovla/tokyodark.nvim#30]
Does the theme have markdown highlights?
as for me the markdown file is pure pale without any colors.

**Comment by niksingh710** [comment]
it works nicely in tokyonight theme

**Comment by tiagovla** [comment]
Hi! Do you have a small snippet of markdown and how it looks like in both themes?

**Comment by niksingh710** [comment]
tokyonight
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/ba7a6e60-a138-4724-9fd1-92efc360aa66)

tokyodark
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/6aa3452b-0586-4010-b4a3-aa58917d489d)

**Comment by tiagovla** [comment]
![image](https://github.com/tiagovla/tokyodark.nvim/assets/30515389/4d58ad0d-1f3c-4497-bd8e-44b806931f06)

That's weird. Mine has highlights with and without treesitter. Is this happening to all other filetypes?

**Comment by niksingh710** [comment]
```lua
return {
  {
    "tiagovla/tokyodark.nvim",
    -- enabled = false,
    priority = 1000,
    lazy = false,
    opts = {
      -- custom options here
      transparent_background = true,
      gamma = 1.00,
      styles = {
        comments = { italic = true },
        keywords = { italic = true },
        identifiers = { italic = true },
        functions = {},
        strings = {},
        variables = {},
      },
      terminal_colors = true,
      custom_highlights = function(highlights, colors)
        return {
          TelescopeMatching = { fg = colors.orange },
          TelescopeSelection = { fg = colors.fg, bg = colors.bg1, bold = true },
          TelescopePromptPrefix = { bg = colors.bg1 },
          TelescopePromptNormal = { bg = colors.bg1 },
          TelescopeResultsNormal = { bg = colors.bg0 },
          TelescopePreviewNormal = { bg = colors.bg0 },
          TelescopePromptBorder = { bg = colors.bg1, fg = colors.bg1 },
          TelescopeResultsBorder = { bg = colors.bg0, fg = colors.bg0 },
          TelescopePreviewBorder = { bg = colors.bg0, fg = colors.bg0 },
          TelescopePromptTitle = { bg = colors.purple, fg = colors.bg0 },
          TelescopeResultsTitle = { fg = colors.bg0 },
          TelescopePreviewTitle = { bg = colors.green, fg = colors.bg0 },

          PMenu = { bg = "none" }, -- make cmp menu transparent
        }
      end, -- extend highlights
    },
    config = function(_, opts)
      require("tokyodark").setup(opts) -- calling setup is optional
      vim.cmd("colorscheme tokyodark")
    end,
  },
}
```
This is my config.
I tried my same config in minimal.lua and it worked.
now i am confused what is overriding the highlights for markdown and specifically overriding tokyodark one's as it is not happening with other themes.

**Comment by niksingh710** [comment]
@tiagovla i figured out the culprit.
```lua
{
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPost", "BufNewFile" },
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = "all",
        highlight = {
          enable = true,
          use_languagetree = true,
          additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        auto_install = true,
        sync_install = true,
      })
    end,
  },
```

in my treesitter config if `additional_vim_regex_highlighting` is false then tokyodark markdown highlight is not working.
but works for other theme.

**Comment by niksingh710** [comment]
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/15cc5948-3c5e-4868-9eb4-4bafa65f2f27)
how you got them to be circle? like any plugin that is concealing them?
and which font?

**Comment by shreyas-a-s** [comment]
I also am someone preferring treesitter over vim_regex_highlighting because I think vim's way makes the highlighting a bit slower when used along with treesitter.

I am currently using thise treesitter code to set vim highlighting only on markdown files.
```
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { "markdown" },
    },
```

It would be nice to see what is causing this issue in tokyodark.

**Comment by tiagovla** [comment]
I will look into it, thanks for the temporary fix suggestion.

**Comment by shreyas-a-s** [comment]
I think I found the culprit. It was simply the lack of treesitter 'markup' highlights. See this video:

https://github.com/tiagovla/tokyodark.nvim/assets/137637016/d460d2fc-6cd3-4111-8065-e0348488526f

In the first part of video, when only the treesitter highlight is enabled, it required that markup.something.markdown highlights are set. Otherwise no colors will be shown. In the second part though, when using additional vim highlights for markdown - the temporary fix i suggested - vim's native syntax highlighting is used and tokyodark has the highlighting needed for that already [here](https://github.com/tiagovla/tokyodark.nvim/blob/a21ec7417b1ba08449ae4cfbf1f6045138bf1d54/lua/tokyodark/highlights.lua#L371-L398). Hence colors are shown.

So the fix would be addition of treesitter specific highlights. An example I made using links to tokyodark's existing highlights:

```lua
["@markup"] = { link = "@none" },
["@markup.emphasis"] = { italic = true },
["@markup.heading"] = { link = "Title" },
["@markup.heading.1.markdown"] = { link = "markdownH1" },
["@markup.heading.2.markdown"] = { link = "markdownH2" },
["@markup.heading.3.markdown"] = { link = "markdownH3" },
["@markup.heading.4.markdown"] = { link = "markdownH4" },
["@markup.heading.5.markdown"] = { link = "markdownH5" },
["@markup.heading.6.markdown"] = { link = "markdownH6" },
["@markup.link"] = { link = "markdownLinkText" },
["@markup.link.label"] = { link = "SpecialChar" },
["@markup.link.label.symbol"] = { link = "Identifier" },
["@markup.link.url"] = { link = "markdownUrl" },
["@markup.list"] = { link = "markdownListMarker" },
["@markup.list.checked"] = { fg = "#73daca" },
["@markup.list.markdown"] = { link = "markdownListMarker" },
["@markup.list.unchecked"] = { fg = "#7aa2f7" },
["@markup.strikethrough"] = { strikethrough = true },
["@markup.strong"] = { bold = true },
["@markup.underline"] = { underline = true },

```

See the implementations in tokyodark by folke [here](https://github.com/folke/tokyonight.nvim/blob/c025baf23b62f044eff1f4ef561c45de636f0e32/extras/lua/tokyonight_night.lua#L334-L392) and that in my tokyodark fork [here](https://github.com/shreyas-a-s/neodarker.nvim/commit/14f41748c57bb297763935a8f04b387b48789ca9).

**Comment by tiagovla** [comment]
Funnily enough, I have `additional_vim_regex_highlighting` set to false but I still get markdown highlights from treesitter. I will check those out. Maybe I should add a minimal configuration with only Tokyodark and Treesitter so that other issues can be easily reproduced.

**Comment by shreyas-a-s** [comment]
Oh. That definitely is pretty weird. But as is the case of any code that we put into our lil computers.

Check it out when you have time and you feel like to. I am very curious to know the reason.

That's a really nice idea. Since the colors are mostly dependent only on the colorscheme and treesitter, I think such a minimal config would be a great addition to the project.

**Comment by tiagovla** [comment]
Using this
```markdown
# heading 1
## heading 2
### heading 3
#### heading 4 
##### heading 5
###### heading 6

[link](www.github.com)
**bold**
*italic*
***bold and italic***


1. item 1
2. item 2

- item 1
- item 2

[ ] box
[x] checked box

```python
    def hello() -> str:
        return "hello"
```

shows like this using nvim 0.10 with the minimal config I added to the bug report template

![image](https://github.com/tiagovla/tokyodark.nvim/assets/30515389/1f033cf7-bffe-4f99-bbee-a0703afb3a00)

The ones that need better highlighting are the link and checkbox. Also, obsidian.nvim was adding extra highlights for me, I guess.

**Comment by shreyas-a-s** [comment]
Yeah. That I also noticed. Not all highlights are 'off', just a few of them.

Obsidian, yeah it makes sense. I kinda like those highlights and conceals provided by it. I might as well try it.

I agree. Adding all of them highlights would be the way to go just for the completeness.

Also a small feature idea from my side would be to color differently the levels of headings like H1, H2 so as to distinguish them easily and for adding a little flair to the code. I like it that way. But I undestand everybody's tastes differ and there is custom highlights option in the colorscheme setup function for anybody to tweak to their liking. Hence no need to change if you prefer the same color.
