### ISSUE TITLE
The todo comments don't work.

### ISSUE THREAD

**Issue by ashin-15** [tiagovla/tokyodark.nvim#7]
This is tokyodark:
![2021-10-12-133649_258x154_scrot](https://user-images.githubusercontent.com/83629316/136917493-2b186335-e402-47e8-8e16-832dbb9ded27.png)

This is onedarker:
![2021-10-12-134934_195x173_scrot](https://user-images.githubusercontent.com/83629316/136919102-ef83974b-ee6d-4a37-ae9f-75ce26c279e8.png)

The todo comments some don't work. 
Love this colorscheme.

**Comment by ashincoder** [comment]
sorry
https://github.com/LunarVim/onedarker.nvim

**Comment by tiagovla** [comment]
Tbh I did try that, but I think it's way too much. Specially using medium size instead of regular.

![cmp](https://user-images.githubusercontent.com/30515389/137236032-bc462f9c-2753-41fa-9e0b-af5729675d6c.png)

If you want to customize it in your config, you can use this after loading the theme:

```lua
local function replace_hl(group, val)
    local ns = vim.api.nvim_create_namespace('tokyodark')
    local res = vim.api.nvim_get_hl_by_name(group, true)
    res = vim.tbl_extend("force", res, val)
    vim.api.nvim_set_hl(ns, group, res)
end

local groups = {"commentTSDanger", "commentTSNote", "commentTSWarning"}
for _, group in ipairs(groups) do replace_hl(group, {bold = true}) end
```

Btw, these are the groups used by treesitter, Todo is linked if those are not defined.
https://github.com/tiagovla/tokyodark.nvim/blob/c1052e548db1b6107155d0b7f3aa577a12d2464a/lua/tokyodark/highlights.lua#L187-L189
